apiVersion: v1
kind: Secret
metadata:
  name: budgify-api-auth
type: Opaque
data:
  ConnectionStrings_budgify_db: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlOyBVc2VyIElkPXBvc3RncmVzOyBEYXRhYmFzZT11c2VyOyBQYXNzd29yZD1wb3N0Z3JlczsgUG9ydD01NDMyOw==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgify-api-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgify-api-auth                       associa o deployment ao pod que possui a mesma label
  template:
    metadata:
      labels:
        app: budgify-api-auth
    spec:
      containers:
        - name: budgify-api-auth-container
          image: ecmiraldo/budgify:master
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          ports:
            - containerPort: 5072
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "5072"
            - name: ConnectionStrings_budgify-db
              valueFrom:
                secretKeyRef:
                  key: ConnectionStrings_budgify_db
                  name: budgify-api-auth
              #value: "Host=postgres-service; User Id=postgres; Database=user; Password=postgres; Port=5432;"
